name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm run test
